[build]
  command = "yarn install --ignore-engines && npx --yes expo-cli export:web"
  publish = "web-build/"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200